__default__:
    cpus: 2
    mem: 8g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:1

ping_12:
    cpus: 32
    mem: 64g
    partition: norm
    time: '100:00:00'
    scratch: lscratch:1000

ping_3:
    cpus: 50
    mem: 64g
    partition: norm
    time: '200:00:00'
    scratch: lscratch:1000
