__default__:
    cpus: 2
    mem: 24g
    partition: quick,norm
    time: '4:00:00'
    scratch: lscratch:1

ping_12:
    cpus: 16
    mem: 120g
    partition: norm
    time: '100:00:00'
    scratch: lscratch:1000

ping_3:
    cpus: 16
    mem: 120g
    partition: norm
    time: '100:00:00'
    scratch: lscratch:1000
